### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by deepu-afk** [adityaSharma6356/IdeaBox#1]
When creating an idea
If you add two topics you can't undo your choices from the list but if you go back and reopen the list the selection is gone and selecting the same topics selected before results in the app crashing.

**Comment by adityaSharma6356** [comment]
Fixed 
issue : the view was not being updated as the check was changing but actual value was changed and hence causing index out of bounds error when reopened

solution : Added controlled setter and deletion methods in category selection list and shifted to use SnapshotStateList in viewmodel instead of mutable state of list for smoother updates in view
